config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: {minimum: 6}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :set_list, only: [:create]

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list_id = @list.id
      if @bookmark.save
        redirect_to list_path(@list)
      else
        render :new, status: :unprocessable_entity
      end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list_id)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @movie = Movie.new
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
      if @list.save
        redirect_to list_path(@list)
      else
        render :new, status: :unprocessable_entity
      end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
         <%= link_to lists_path, class: "navbar-brand" do %>
      <%= image_tag "cinema.png" %>
    <% end %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                <%= link_to "Nouvelle liste", new_list_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Listes", lists_path, class: "nav-link" %>
              </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('banner.jpg') %>);">
      <div class="container">
        <h1>Créez vos collections de films cultes</h1>
        <p>Faites des listes, ajoutez y vos films, consultez quand vous voulez.</p>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="container my-4">
    <h2 class="text-center">Mes listes</h2>
  </div>

  <div class="row">
    <% @lists.each do |list| %>
        <div class="col-md-4 mb-4">
          <%= link_to list_path(list), class: "text-decoration-none" do %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : 'https://conwayyao.com/wp-content/uploads/2015/07/Cinema_Banner.jpeg' %>)">
              <h2>
                <%= list.name %>
              </h2>
            </div>
          <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container mt-4">
  <div class="row justify-content-center ">
    <div class="col-md-6">
      <%= simple_form_for @list do |f| %>
        <%= f.input :name, label: "Nom de la liste", input_html: { class: 'form-control' } %>
        <%= f.input :photo, as: :file, label: "Ajoutez une image", input_html: { class: 'form-control' } %>
        <%= f.submit "Créer la liste", class: "btn btn-submit mx-auto d-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container mb-4 pt-2">
  <div class="row align-items-center">
    <div class="col-3"></div>
    <div class="col-6 text-center">
      <h2 class="mb-0"><%= @list.name.upcase %></h2>
    </div>
    <div class="col-3 text-center">
      <h3>Ajoute ton film</h3>
      <div class="d-flex flex-column align-items-center form">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, label:"Commentaire", input_html: { class: 'form-control'} %>
          <%= f.association :movie, label: "Film", input_html: { class: 'form-control' } %>
          <%= f.submit "Ajouter un film", class: "btn-submit" %>
        <% end %>
    </div>

    </div>
  </div>
</div>



<div class="container mt-5">
  <div class="row justify-content-center">
    <% @list.movies.each do |movie| %>
      <div class="col-md-4 mb-4 d-flex">
        <div class="card h-100 movie_card  w-100">
          <img src="<%= movie.poster_url %>" class="card-img-top movie-poster" alt="<%= movie.title %>">
          <div class="card-body d-flex flex-column">
            <h5 class="card-title"><%= movie.title %></h5>
            <p class="card-text"> ⭐ <%= movie.rating %></p>
            <p class="card-text"><%= movie.overview %></p>
            <% movie.bookmarks.where(list_id: @list.id).each do |bookmark| %>
              <div class="mt-2 d-flex justify-content-between align-items-center">
                <span> ❝ <%= bookmark.comment %> ❞</span>
                <%= link_to "❌", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "You are going to delete the movie, are you sure ?" } %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>